name: PlotWeekends

on:
  workflow_dispatch:
  schedule:
   - cron: '*/5 7-19 * * 6,0' #Every 5 minutes, between 09:00 AM and 09:59 PM, only on Saturday and Sunday

jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      # Set up environment variables
      - name: Setting up environment
        run: |
          echo "ISSUE_NUMBER=${{ github.event.issue.number }}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "REPOSITORY_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      # Set up a Python 3.8 (64-bit) instance
      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"

      # Use pip to install the dependencies and then run the script
      - name: pip install dependencies
        run: |
          pip install -r code/requirements.txt

      - name: Run PlotData.py
        run: |
            python code/PlotData.py
      # Create new commit with the changed files and push it to GitHub
      - name: Commit and push changes
        if: ${{ always() }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🐐 Renewed Plot!"
          git push
